### ISSUE TITLE
Rethink E-Mail notification on MAC change

### ISSUE THREAD

**Issue by sebschrader** [agdsn/sipa#108]
We want to prevent account sharing, I get that, but are those E-Mail notifications really the right way to do this?

What happens, if an admin receives that mail? Either she has set up a filter and the mail will be moved into a folder in which it won't be read or the she has noise in her inbox and will just mark it is read without reading it.

The only incidents I can imagine, where mails would be helpful and actually read, are:

1. someone rapidly changes his MAC address (daily, weekly, whatever), in which case we will receive a lot of mails by that user
2. an admin decides to do some investigations based on some suspicions and searches her mail archive for MAC change notifications

In both cases other means would be more appropriate. A MAC change event log for example could be used to rate limit MAC changes and could be queried by admins if investigations are necessary.

**Comment by lukasjuhrich** [comment]
I will drop the sending of a mail. We could rely on the logging messages, see my commit (to be pushed).

**Comment by sebschrader** [comment]
What about the changes to the warning we discussed offline?

We talked about making the MAC change form a two-step form with the warning and checkbox to acknowledge the warning in the first step and the actual form in the second step. In this case the warning would not have to be wrapped inside a colored box.

**Comment by lukasjuhrich** [comment]
@sebschrader I consider this to be a separate issue (see #115). Thanks for reminding me!
