### ISSUE TITLE
Add hook for content pulling

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#110]
The current static interval of every 5 minutes is not very satisfying and under critical circumstances quite slow.

**Comment by lukasjuhrich** [comment]
An interval of five minutes is not slow at all for something being run 24/7 . Please explain what you would call such a “critical circumstance”.

Otherwise I will close the issue after an appropriate amount of time.

**Comment by toothstone** [comment]
Besides urgent warnings, this is especially annoying when writing/editing content, if you can't or don't want to run a SIPA instance locally. It can take 5 minutes until your content appears online, and if you made any mistake it can take another 5 or 10 minutes to fix it and confirm the result.

**Comment by lukasjuhrich** [comment]
@toothstone The used syntax is markdown, there are plenty of possibilities to render it in advance.

Raising the update speed to an insane amount should not be an instrument to ensure submitting correct markdown files in the first place. It is just technically not something that should be done.

Keep in mind that in the long run we might implement a live editing solution, so these inconveniences will disappear.

What exactly were the mistakes you had to fix after you commited them?

**Comment by toothstone** [comment]
> The used syntax is markdown, there are plenty of possibilities to render it in advance.
There is custom stuff in our content pages, especially the metadata header section.

> Raising the update speed to an insane amount should not be an instrument to ensure submitting correct markdown files in the first place. It is just technically not something that should be done.
Sure, that was never my intention and would be a horrible design. I think a "push" solution should replace the current "pull" mechanism.

> Keep in mind that in the long run we might implement a live editing solution, so these inconveniences will disappear.
I was not aware of this, and I'm not sure if such a complex feature is really desirable. But that's a different story, and not everyone will be using this, especially since git is a well known (CLI-)tool for most of us.

**Comment by janLo** [comment]
Yust Providence a http endpoint that can be used (with a secret token or any authentication) from a git-hook to start fetching. So you can use the hook for normal and instant updates and set the interval for periodic updates to a hour or so (just to catch the case that a update was missed because of a network error between the repo and the Installation for example).

**Comment by lukasjuhrich** [comment]
@janLo This seems to be an elegant solution, I will stick to this.

**Comment by janLo** [comment]
You should use the spooler interface for this to prevent races and http timeouts when the repo is busy. Details are shown here: https://github.com/agdsn/sipa/issues/19#issuecomment-100716267
