### ISSUE TITLE
Auto update traffic gauge

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#112]
The gauge could maybe update without refreshing the whole website.

**Comment by gwTumm** [comment]
I dont think this is worth to implement. The site was not designed as a single page application with dynamic content in mind. If a user wants to get regular updates, he can still install one of the trafficplugins.

Alternatively, one could utilize html5 Server sent events and html5 notifications which would make the trafficplugins obsolete while providing morr features and being easier to maintain.

**Comment by gwTumm** [comment]
Even better than local notifications: https://developers.google.com/web/updates/2015/03/push-notificatons-on-the-open-web . That'd be awesome.

**Comment by toothstone** [comment]
Sure, notifications would be even better.

**Comment by lukasjuhrich** [comment]
@gwTumm How would sending push notifications make the traffic plugins obsolete? They provide completely different functionality than sipa, namely to have an auto-updating icon in your browser.

Coming back to an auto-updating traffic gauge -- do you think this would be nice to implement using push notifications, or do you stick to the decision “The site was not designed as a single page application with dynamic content in mind.”? These statements seem to contradict each other.

**Comment by lukasjuhrich** [comment]
Closing as the gauge has been removed.
