### ISSUE TITLE
Display user ID at /usertraffic

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#113]
The Wundtstraßen drupal used to show the user ID at /usertraffic, which made it much easier for people who forgot their password.

**Comment by lukasjuhrich** [comment]
@toothstone What does the `user_id` have to do with the password? Do you mean that people who forgot their password got easier access to their `user_id`?

But anyway, good idea!

**Comment by mmarx** [comment]
Previously, users could look up their user ID on the traffic page, without needing to enter their password.

**Comment by lukasjuhrich** [comment]
So it's just a convenience feature, alright.

**Comment by toothstone** [comment]
We receive quite some mails from people who don't know their IDs, I think we should reimplement this asap.
