### ISSUE TITLE
Message ID missing in sent mails

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#117]
Apparently, SIPA does not set a proper message ID in mails, which breaks threading in my mail client (thunderbird 38.3.0-1).

**Comment by mmarx** [comment]
This might come in handy: https://www.jwz.org/doc/mid.html

**Comment by janLo** [comment]
There is a RFC for that: [rfc2822](http://tools.ietf.org/html/rfc2822.html) and its implemented in the standard library as [email.utils.make_msgid([idstring])](https://docs.python.org/2/library/email.util.html#email.utils.make_msgid). So you should replace your code with hat (less code is better code).
