### ISSUE TITLE
Collapsed navbar overflowing

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#120]
When the collapsed navbar is displayed, seemingly the language cannot be selected. In reality though, it is just hidden and reachable when scrolling down.

**Comment by janLo** [comment]
As described in #111 ihis is not only a problem with the language - it concerns all Navigation points that does not fit on the device screen. It renders the site complete unuseable on small devices (the devices the users use to get information when the network on their computer is broken). Maybe reopen #111?

**Comment by lukasjuhrich** [comment]
#111 is still a duplicate of #104.

Also, this is just a placeholder as it is fixed in my local commits.

**Comment by janLo** [comment]
Then you maybe should not open issues that describes exactly the same (or at least a complete part) of issues you closed as duplicate a few days ago just to generate issue-traffic. And even if you do that you should mention that your new issue does not describe any new issue but only a defect that is already well-known and topic of two other existing issues. So people do not waste time do point out that they already provided advanced information about that issue.

**Comment by lukasjuhrich** [comment]
I should have referenced this is a specific #104 as it is kind of the parent issue here. Sorry for the confusion.

I do not care about issue traffic. If I open a new issue, I do so because I am sure that it has not been recorded in an appropriate specificity. But as you mentioned, reference was missing here and should've been provided.

**Comment by toothstone** [comment]
Since scrolling is now disabled, menu items at the bottom are now not just hidden, but actually unreachable. Reopening.

**Comment by lukasjuhrich** [comment]
@toothstone could you provide more information (the display size of your device)? I would not have pushed it if I would not have tested it, so it is definitely not reproducible by me.

I believe that your device does not have insufficient height.
But that cannot be resolved: Either you **do** enable scrolling, or you **don't** by setting an appropriate `max-height`.
- If you don't, you cannot scroll if the height of the menu exceeds what your device is capable of displaying.
- If you do, you end up having people complaining about how you cannot reach the bottom entry although you actually can, you just have to scroll down.

To be fair though, one could set `max-height` to some other value than the default one to ensure not to “stop” when a menu entry just finished, to intuitively show that it “goes on” below.

Implementing something like arrows pointing down would require a change being more than just non-trivial.

**Comment by lukasjuhrich** [comment]
On the other hand, it would be trivial to just add an entry to the top of the menu suggesting to scroll down.

Also, one could easily check for the device's height to switch between a cut and an uncut version of the menu.


![screenshot](http://i.imgur.com/CzmZFtx.png)
