### ISSUE TITLE
Text not contained in sidebar boxes

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#121]
The layout of text in the righthandside boxes is terrible on lower resolutions now, text is neither wrapping nor shrunk. Also is the traffic gauge much smaller than before, imho too small.

**Comment by lukasjuhrich** [comment]
@toothstone Regardless of your contributions, something like this is significantly unconstructive.
Especially concerning ui bugs or inconveniences, please provide
- a screenshot depicting what you are talking about
- a description which of these elements you are concerned with and, more importantly,
- a suggestion of what you suggest to solve this problem.

The issue with ui bugs is that if I don't know _to what_ I shall change the UI, i either
- break something else or create other conveniences, or
- spend hours and hours ((responsive) UI design is not easy) more looking at the page and planning how it might have to look like than actually changing something, eventually having my solution declined and being told that Y would be better.

This causes an enormous waste of time we cannot afford at the moment.

**Comment by toothstone** [comment]
![box_sipa](https://cloud.githubusercontent.com/assets/4670824/10302755/190d75fc-6c0f-11e5-98c7-eaf50458e2b4.png)

**Comment by lukasjuhrich** [comment]
I believe the fix for this is not displaying the sidebar at all, but rather display the solution smaller devices would fall back to anyway.

**Comment by lukasjuhrich** [comment]
Closing, same reason as in #104
