### ISSUE TITLE
Display our name in mobile design

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#122]
Currently only our logo is displayed at low width, which is not really enough to identify the website as ours.

**Comment by janLo** [comment]
This is a duplicate of #111

**Comment by toothstone** [comment]
You're right, nevertheless this has not been solved (but closed) and imho #104 is (at least by now) about the layout/arrangement of content. I also don't see the advantage of one big, confusing thread when the topic can be easily split into several issues.
