### ISSUE TITLE
Add possibility to contact the executive board

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#125]
There should be a Vorstand option on the contact form with a hint that this is not a support mail.

**Comment by toothstone** [comment]
> There should be a Vorstand option on the contact form with a hint that this is not a support mail.

Please not o_O. We will provide the contact information on a content
page, otherwise this will only cause mislead mails (hint: nobody reads
hints).

**Comment by lukasjuhrich** [comment]
@toothstone It will be read Indeed, if the hint pops up just when you select “Vorstand” and has a distinctive color like red / yellow. Also, having bold text suggesting that internet problems will not be solved there will be noticed for sure. If that is not enough, I can implement a [modal](http://getbootstrap.com/javascript/#live-demo). There are possibilities to get this information to our members and to keep our mailing list clean.

Please be aware that this issue was not just a small thought of me, but rather a request that came up in the Vorstandssitzung yesterday, so it should be taken seriously.

It should be easy for partners to contact us, and I believe *not* including the Vorstand in the contact form would make this too hard. Our partners have limited time as well and should not have to navigate through our content to find a mail address, when they could just type in text in a contact form and go on with their agenda.

**Comment by toothstone** [comment]
Ok then. The modal seems a little too interruptive to me.

I will keep track of the use-misuse-ratio here ;)
