### ISSUE TITLE
Improve finance and payment information

### ISSUE THREAD

**Issue by sebschrader** [agdsn/sipa#127]
Currently the semester contribution amounts are shown for all division in a content page https://github.com/agdsn/sipa-content/blob/master/membership/semester_contribution.de.md and the account details for each division are shown in the sidebar on the left after a division has been selected. This is confusing.

1. Account information in the sidebar is very difficult to find.
2. The user must search for her division in the content page and select it in the navbar, this is redudant
3. Users should not be bothered with the different contributions in our divisions

Therefore I propose:

1. Like the account details, the semester contributions should only be shown after the dormitory has been selected by the user.
2. The dropdown menu and the information shown after selecting an item in the dropdown menu should be moved from the sidebar to main content area. This may not be possible with content pages I was told, therefore a custom module may be necessary for this.

**Comment by lukasjuhrich** [comment]
This has been fixed by @sebschrader using appropriate changes in sipa-content. Closing.
