### ISSUE TITLE
Do not display traffic for inactive users

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#130]
Because the IP is reassigned, traffic data is displayed for exactive users. This is confusing and wrong.

**Comment by lukasjuhrich** [comment]
@mmarx I could you please test whether traffic data is displayed for you? I am not sure if the user's `computer`s are still in the database.

**Comment by mmarx** [comment]
Traffic data is still displayed, even though the IP has long since been reassigned.

**Comment by lukasjuhrich** [comment]
@mmarx could you please test this on sipa-testing, since the ORM implementation is not on the `master` yet? Thanks!

**Comment by mmarx** [comment]
I did, and I'm still seeing traffic data.

**Comment by lukasjuhrich** [comment]
@mmarx Alright then, thanks for testing! What are valid statūs? 0, 1, 7, 12? is there any kind of reference?

**Comment by mmarx** [comment]
In addition to those already defined:
 - 3: mail only, blocked
 - 8: moved out
 - 10: mail only

**Comment by lukasjuhrich** [comment]
Correction: I meant 1, 2, 7, 12.

But 3, 8 and 10 should *not* be allowed for trafficdata, just as 9 (formerly active).

This leaves
- 1: ok
- 2: not payed
- 7: abuse
- 12: traffic
as valid statūs for viewing trafficdata. Correct @mmarx ?

**Comment by mmarx** [comment]
Yeah, right, but 3, 8, and 10 need te be added anyways.

**Comment by lukasjuhrich** [comment]
LOL.

Just found this after already having fixed the later added duplicate #185 

Closing.
