### ISSUE TITLE
Link to user page on semester_contribution page broken

### ISSUE THREAD

**Issue by KaliszAd** [agdsn/sipa#131]
Getting Error 404: https://agdsn.de/sipa/pages/membership/semester_contribution

The link is located in the following paragraph:
>You can check your payment status on your **user page**. You have to login with your username and > password. When the payment has reached our bank account it will be allocated to your account by an > automated software system. If your payment status didn´t update after three days, please come to
> during our office hours and bring a bank account statement with you which mentions the transfer.

**Comment by lukasjuhrich** [comment]
This is an issue for  `sipa-content`. Besides, the links seem to be fixed.
