### ISSUE TITLE
Redirect to login page

### ISSUE THREAD

**Issue by janLo** [agdsn/sipa#147]
If you follow a link in the content to a page you only can access if you're logged in, you currently gent an error message. It would be more usable to redirect directly to the login page and display a flash-message there. The sed Flask-login have already [support for this](https://flask-login.readthedocs.org/en/latest/#customizing-the-login-process). After a successful login there can easily sent a Location header to the original requested page.

At least you can provide a link to the login page in at the error page, because on small screens the "login-button" is not instantly visible without searching in a menu.

![sipa](https://cloud.githubusercontent.com/assets/96146/10846504/781cada6-7f10-11e5-9b6d-f37d48b1d0ab.png)

**Comment by lukasjuhrich** [comment]
@janLo Can you provide some guidelines concerning status codes and redirection? I hav been confused quite recently about which status codes to send while you're actually redirecting, or when writing the `Location` header will have an effect. Currently, I believe the returned status is `200 OK`, which is quite wrong.

**Comment by sebschrader** [comment]
What's your problem?

Flask handles the status code and `Location` headers for you.

**Comment by toothstone** [comment]
I changed the button in https://github.com/agdsn/sipa/commit/77815d2ac3bf34028455eb4f728e268daa8bedd8

Will look into the redirection, since the usersuite got useful permalinks we now have a real use case for this feature.

**Comment by sebschrader** [comment]
There is a better way. Flask-Login provides the [`login_view` mechanism](https://flask-login.readthedocs.io/en/latest/#customizing-the-login-process).

When Flask-Login determines, that a login is required, e.g. `login_required` decorator, and a `login_view` is defined, it will redirect to this view instead of returning a 401.

Please read the docs, people.

**Comment by toothstone** [comment]
Thanks for the link @sebschrader, I had not even started on this at that time.
