### ISSUE TITLE
Changing UI language results in invalid redirect

### ISSUE THREAD

**Issue by fgrsnau** [agdsn/sipa#149]
The language switching logic seems to rely on the request’s Referer-header.

If the browser doesn’t send a Referer-header (my browser doesn’t :-D), the user is redirected to /sipa/None and a 404 is rendered.

**Comment by lukasjuhrich** [comment]
Thanks a lot for reporting! The redirection explicitly used the referer, although for such cases we already implemented a separate function (`redirect_url(default='generic.index')`). It just had to be called instead of using the referer explicitly.
