### ISSUE TITLE
Configuration frontend

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#15]
When creating the possibility to activate / deactivate / modify features, there should be a configuration frontend for these purposes.

**Comment by sebschrader** [comment]
Which features are you referring to?

**Comment by lukasjuhrich** [comment]
Features that have to be modified (considering the code) by another “provider” (in our case anocther section) in order to run Sipa. These features are (i.e.):
* User authentification
* User data (mac, ip, name, etc.)
* basically everything **“Wu-specific”**.

Since we have to elaborate some configuration method to enable/disable/load certain modules and methods, adding a possibility to do so via the gui might be a good idea.

This idea has been mentioned by @cooox to me, perhaps he can comment on this if I should have understood something wrongly.

**Comment by lukasjuhrich** [comment]
Rethinking this: I do not really know what would require or profit from a GUI, either.
Perhaps I forgot something you mentioned @cooox?
However, I'll close this issue at first.

**Comment by cooox** [comment]
> Since we have to elaborate some configuration method to enable/disable/load certain modules and methods, adding a possibility to do so via the gui might be a good idea.

You said it yourself! The GUI would remove the necessity to change code (imports). 
What's with config variables?

**Comment by lukasjuhrich** [comment]
But configuring which section you choose for this instance of Sipa is a one-time-thing which is done when rolling out, so there is no need for availability via a GUI.

The configuration variables are (as it seems) going to be retrieved from the environment, which is an easy setup.
And how often do you have to change, say, the ip address of your LDAP server?
