### ISSUE TITLE
Cookie Warning

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#164]
Sipa will need a cookie warning.

Feel free to work on this issue.

**Comment by toothstone** [comment]
This might be helpful: https://github.com/cfenollosa/eu-cookie-law

**Comment by fgrsnau** [comment]
I’m not really interested in fixing this by myself (not much spare time currently). Seems like @sgeisler is willing to look into this. The issue is also a low hanging fruit and an easy entry point into the development of Sipa.

**Comment by fgrsnau** [comment]
Possibly we do not need such a cookie warning at all. See #292 for more details.

Someone really should read the legal documents to give a concrete answer ;-P

**Comment by sebschrader** [comment]
I don't think we actually need a cookie warning at all. See [here (German)](http://blog-it-recht.de/2015/09/14/eu-cookie-richtlinie-das-ist-der-aktuelle-handlungsbedarf-wenn-sie-einen-shop-betreiben/).

**Comment by lukasjuhrich** [comment]
Closing as no longer relevant.
