### ISSUE TITLE
'No data' in traffic graph for unauthenticated users

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#165]
When connecting from a AG DSN-IP without authenticating, the traffic graph only shows 'No data'.

**Comment by lukasjuhrich** [comment]
@toothstone This has been resolved by c7393d0656244f6a04cfcec6f28818cea4619c8d I believe, but I have to fix something in `testing` to test it before updating `stable`.

**Comment by lukasjuhrich** [comment]
@toothstone please reproduce, but I am sure it is resolved now since I pushed the according commit (which is e9d9c42494515b1af0bce28a6ebf31ddd534ec70)

**Comment by toothstone** [comment]
Looks good now :)

**Comment by lukasjuhrich** [comment]
@toothstone Lovely! ♥
