### ISSUE TITLE
Re-Implement usage of connect_timeouts for SQL databases

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#168]
Since I could not find a trivial way to tell sqlalchemy to use according `connect_timeout`s on the underlying engine, this has to be elaborated.

**Comment by sebschrader** [comment]
Just listen on the MySQL connection pool for `connection` events and issuing the the appropriate `SET` query.

Don't follow the examples there blindly. Listening on the Pool class is probably wrong, you should listen on the appropriate pool instance.

http://docs.sqlalchemy.org/en/rel_1_0/core/event.html

**Comment by lukasjuhrich** [comment]
@sebschrader This is about the connect_timeout, i.e. the max. time to wait _before_ a connection to a mysql server has been established. It cannot be set executing a `SET` query, the only possibility is to tell the MySQLpython driver the arguments.

**Comment by sebschrader** [comment]
Ahh. Then it's easy, just pass connect_timeout as a query parameter in the connection URI, i.e.:
```
>>> from sqlalchemy import create_engine
>>> e = create_engine('mysql://bla:blub@8.8.8.8/foodb?connect_timeout=4')
>>> e.connect()
…
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, 'Can\'t connect to MySQL server on \'8.8.8.8\' (4 "Interrupted system call")')
```

**Comment by sebschrader** [comment]
This will probably only work with the `mysqldb` and `pymysql` connectors and not with other connectors like `mysql-connector`.

**Comment by lukasjuhrich** [comment]
@sebschrader yes, that's how it has been implemented. Because I switched to using Flask-SQLAlchemy, I tried to figure out a way to implement it there, but I can't access the engine or modify the initialization process of the engine without manually patching. Predefined possibilities to pass options don't exist.

Thus, it seems I will have to implement session scoping myself in SQLAlchemy and drop the usage of Flask-SQLAlchemy.

**Comment by sebschrader** [comment]
This doesn't make sense to me. Why shouldn't it work with Flask-SQLAlchemy? All you need to do, is use an appropriate URI and Flask-SQLAlchemy expects URIs in either the simple `SQLALCHEMY_DATABASE_URI` option or the `SQLALCHEMY_BINDS` option.

**Comment by lukasjuhrich** [comment]
Alright, I didn't know the parameter could be passed in the URL directly.
