### ISSUE TITLE
Required Name field for Contact form

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#172]

**Comment by toothstone** [comment]
During our latest meeting of Division Wundtstraße we realized that some users send mails such as "Internet broken, ermahgerd" without providing any information regarding their identity. Forcing them to enter a name, which will be included in the generated mail, would help in such cases.

**Comment by lukasjuhrich** [comment]
+1, ermahgerd!!!!!

**Comment by toothstone** [comment]
Ermaherd clersd ishu.
