### ISSUE TITLE
Make decision of uwsgi usage easier

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#177]
Currently, if one wants to use uwsgi or not, has some significant consequences regarding how sipa has to be started. To make this easier, there should be a start script, which decides based on an environment variable like `SIPA_USE_UWSGI`, what is run. Also, this “decision” could be passed to sipa to make some things easier, e.g. there does not have to be the monkey-patch when using uwsgi (or the other way around, I always forget).

This could perhaps be combined with the prefix, so keep #176 in mind.

**Comment by sebschrader** [comment]
There must be a way to autodetect this.

**Comment by lukasjuhrich** [comment]
@sebschrader how about:
```python
try:
    import uwsgi
except ImportError:
    use_uwsgi = False
else:
    del uwsgi
    use_uwsgi = True
```
?

**Comment by sebschrader** [comment]
At first sight, I would have rejected this. Because, what if the `uwsgi` module is present on `sys.path`, but then I read the [uWSGI documentation of this module](http://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html) and it states

> The uWSGI server automagically adds a `uwsgi` module into your Python apps.

So it should actually work.

What about:
```python
use_uwsgi = 'uwsgi' in sys.modules
```

**Comment by lukasjuhrich** [comment]
@sebschrader  That seems nice, I didn't know about `sys.modules`.

**Comment by sebschrader** [comment]
You should obviously verify that my suggestion actually works.

`sys.modules` is just a cache of already imported modules, but since the `uwsgi` does not seem to actually exist on the normal Python path and was automagically inserted as the documentation claims, it should be present.

**Comment by sebschrader** [comment]
The variable should be named `under_uwsgi` or similar BTW.

**Comment by lukasjuhrich** [comment]
Closing, since
1. The dev environment uses uwsgi as well, so the “vanilla way” doesn't even have to be supported anymore
2. the problem is essentially solved by an `if __name__ == '__main__'` in `sipa.py`.
