### ISSUE TITLE
Simplify flatpage system

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#178]
Currently, the flatpage system is over-engineered. The category system supports infinite layering, which is not necessary since it cannot be displayed in the navbar. Besides that, there never seemed to be a need for this until now.

Thus, the flatpage system should be refactored.

**Comment by sebschrader** [comment]
Is it really soo complicated that it aggravates maintaining it?

**Comment by lukasjuhrich** [comment]
I want to revisit it. I don't want to change things just for the sake of changing, but see what I can accomplish in the process. A few docstrings for example.
It is very hard to see for example, which attributes a certain class is expected to have, because it very generically tries to retrieve it from some `page.meta`.
It's not too complicated to maintain it, but could be improved here and there.

**Comment by lukasjuhrich** [comment]
That has been solved by the refactorings of #179 . Closing.
