### ISSUE TITLE
Container should pull content updates

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#19]
We need the container to fetch new content automatically. Maybe for the beginning something like a git-pull cronjob is sufficient.

**Comment by lukasjuhrich** [comment]
An important question is how to tell the *running* flask app to reload the pages. I do not know if a cronjob can somehow tell this from “outside” easily.

**Comment by sebschrader** [comment]
I've been suggesting Advanced Python Scheduler https://apscheduler.readthedocs.org/en/latest/ for that purpose previously.

**Comment by janLo** [comment]
You can reload the uwsgi instance by simply sending a sighup to the master process or calling `uwsgi.reload()` from your application (see http://uwsgi-docs.readthedocs.org/en/latest/Management.html).

So you can easily have an http-endpoint that can be triggered by some git-hook or something else to fetch new content and reload the server. The content-getch can be offloaded to the [uwsgi spooler](http://uwsgi-docs.readthedocs.org/en/latest/Spooler.html) to prevent timeouts/races/whatever.

If you really want periodic updates you can simply use the [Uwsgi cron interface](http://uwsgi-docs.readthedocs.org/en/latest/Cron.html).

With all that no extra package or external service is needed.
