### ISSUE TITLE
Become independent of LDAP

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#197]
Currently, `User.get(username)` operates with an LDAP fetch first.  This makes Sipa dependent of the synchronization state of the MySQL backend with the LDAP – which is not always given, e.g. considering the case of newly created users.

The wu Model should thus operate independently.

**Comment by lukasjuhrich** [comment]
This correlates with adapting the newly written HSS-LdapConnector to the wu model.

**Comment by toothstone** [comment]
Obsolete since the wu-model is gone :)

**Comment by lukasjuhrich** [comment]
![](https://i.imgflip.com/xj3w8.jpg)
