### ISSUE TITLE
Make Sipa division-agnostic

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#20]
Many aspects of the content can be changed in a section-agnostic manner. The simplest thing to change would be reformulating strings like „AG DSN Sektion Wundtstraße“ to AG DSN, but I believe there are many things regarding the codi itself that can be done.

The major goal of this is presenting the user different websites (for each section, for instance) which are seemingly the same.

**Comment by sebschrader** [comment]
Please call it division in English and not section.

**Comment by lukasjuhrich** [comment]
Thanks a lot @sebschrader! Correct me if possible, because my English isn't nearly perfect.

By the way, let me add that this issue mostly addresses strings, which makes it kind of a GUI problem.
