### ISSUE TITLE
Add twitter, facebook and github to contact box

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#221]
We should provide a reference to our twitter feed and facebook page as well.

**Comment by toothstone** [comment]
https://www.facebookbrand.com/ and https://about.twitter.com/de/company/brand-assets provide the necessary resources & guidelines.

**Comment by toothstone** [comment]
Maybe we could also add an octocat and link to this repo.

**Comment by lukasjuhrich** [comment]
Why the fuck isn't there an octocat in the emoji box, but a laughing smiley?

**Comment by toothstone** [comment]
![screenshot_20160413_101102](https://cloud.githubusercontent.com/assets/4670824/14486951/177100ec-0160-11e6-9722-5c530c7039ae.png)

**Comment by lukasjuhrich** [comment]
Nice work, thanks for the quick implementation and PR!
