### ISSUE TITLE
Wrong error message: Another user than the one registered for this connection is logged in!

### ISSUE THREAD

**Issue by new2f7** [agdsn/sipa#263]
Wenn ich mich auf meinem Anschluss mit meinem Account einlogge, bekomme ich die oben erwähnte Fehlermeldung (auf deutsch: Ein anderer Nutzer als der für diesen Anschluss Eingetragene ist angemeldet!), obwohl es mein Anschluss ist und ich mich mit meinem Account eingeloggt habe.

**Comment by new2f7** [comment]
could be a dublicate of #254

**Comment by lukasjuhrich** [comment]
@new2f7 exactly, but thanks anyway!
