### ISSUE TITLE
Detailed log of recent payments

### ISSUE THREAD

**Issue by new2f7** [agdsn/sipa#264]
Es wäre von Vorteil, wenn die Mitglieder sehen, wie viel Geld sie noch auf ihrem internen "Konto" haben. Außerdem wäre es gut, wenn die Mitglieder sehen können, welche Zahlungen auf unserem Bankkonto wir ihrem internen "Konto" zugeordnet haben. Allerdings sollten bei den zugeordneten Zahlungen nur Datum und Betrag angezeigt werden, um bei eventuell falsch zugeordneten Zahlungen keine persönlichen Daten preiszugeben. Außerdem sollte ein Zeitstempel mit entsprechender Erklärung angezeigt werden, an dem zuletzt Bankdaten eingelesen wurden, da dies nicht automatisiert geschieht und Mitglieder sich sonst fragen könnten, wieso einen von ihnen getätigte Zahlung noch nicht angezeigt wird.

**Comment by lukasjuhrich** [comment]
This is in some sense a duplicate of #219.
I will change this issue title to „Show detailed information“ or similar, and collect the features in a todo-list.

**Comment by lukasjuhrich** [comment]
This issue requires:
- [ ] A `finance_information` view in the usersuite or similar
- [ ] An additional column for the balance and a button to the detailed log view
- [ ] A method in `BaseUser`: `@active_property finance_balance`
- [ ] The same for the log:  `@property finance_log`
- [ ] The implementation of these methods in `model.hss`
- [ ] The same in `model.wu`

The detailed log view should consist of:
- A table `Date` | `Amount`
- Timestamp / explanation why these are no realtime data
