### ISSUE TITLE
Show MRTG graphs

### ISSUE THREAD

**Issue by new2f7** [agdsn/sipa#265]
Bei Nutzern aus der HSS/IGH sollten die MTRG-Graphen auf Homer angezeigt werden. Dies ist aus Sicherheitsgründen nur möglich, wenn man sich innerhalb des HSS Netzes befindet. Die Graphen wurden auf der alten Website der HSS eingeblendet und werden von den Aktiven und anderen Mitgliedern gewünscht.

**Comment by lukasjuhrich** [comment]
@new2f7 was sind die mtrg-graphen?

**Comment by new2f7** [comment]
http://oss.oetiker.ch/mrtg/

**Comment by lukasjuhrich** [comment]
@new2f7 Wie stellst du dir dieses Feature vor?
- Soll auf `/usertraffic` der Graph eingebettet werden?
- Soll ein Link auf diesen Graphen eingefugt werden?
- Dürfen angemeldete Benutzer außerhalb des Netzes diese Graphen einsehen?

**Comment by mrMaleasy** [comment]
Ja, ich vermisse diesen Graphen auch, bitte unbedingt wieder aufnehmen!

> Soll auf /usertraffic der Graph eingebettet werden?
sehr gerne!

> Soll ein Link auf diesen Graphen eingefugt werden?
nur, wenn es nicht anders geht! Aber besser als nichts...

> Dürfen angemeldete Benutzer außerhalb des Netzes diese Graphen einsehen?
ja, warum nicht. Ist ja immerhin der eigene Anschluss.

**Comment by mrMaleasy** [comment]
Ja, ich vermisse diesen Graphen auch, bitte unbedingt wieder aufnehmen!

> Soll auf /usertraffic der Graph eingebettet werden?

sehr gerne!

> Soll ein Link auf diesen Graphen eingefugt werden?

nur, wenn es nicht anders geht! Aber besser als nichts...

> Dürfen angemeldete Benutzer außerhalb des Netzes diese Graphen einsehen?

ja, warum nicht. Ist ja immerhin der eigene Anschluss.

**Comment by lukasjuhrich** [comment]
Nachtrag: Mir ist erst später klar geworden, dass das für jeden Nutzer ein Tagesverlauf ist.  Ob wir so etwas weiterhin bereitstellen wollen, sollte erst auf einer Teamsitzung geklärt werden, da das Thema kontrovers ist.

**Comment by mrMaleasy** [comment]
Ich war in der Hochschulstraße einmal auf einer Sitzung um dieses Thema anzusprechen. Dort wurde auch erwähnt, dass es wahrscheinlich nicht zurückkehren wird, da diese Daten nicht zwangsmäßig erhoben werden müssen (jedoch waren auch dort alle eher dem alten Graphen zugeneigt).
Ich persönlich fand das immer sehr hilfreich und fände es sehr schade, wenn der MTRG Graph einfach durch das neue Balkendiagramm ersetzt wird. Ich finde das einfach nicht so anschaulich.

**Comment by lukasjuhrich** [comment]
On hold, da das nur mit expliziter Zustimmung des Nutzers geht. Dafür muss ein entsprechender Mechanismus stehen.

**Comment by mrMaleasy** [comment]
Gibt es hierzu Neuigkeiten?
Ist es so schwer, das rechtlich abzuklären?
Kann ich irgendwie helfen?

**Comment by lukasjuhrich** [comment]
@mrMaleasy FYI, wir arbeiten an einem generischeren System zur Speichernug der Trafficdaten in beliebiger Auflösung. Das ist für Graphen mit Tagesverlauf unabdingbar, da wir aus Gründen der Datensparsamkeit auf keinen Fall ohne explizite Einwilligung des Mitglieds so viel speichern können und wollen. Dies bedingt, dass die Auflösung von Mitglied zu Mitglied variieren können muss.

Bis das System steht muss aber noch einiges werden.

**Comment by lukasjuhrich** [comment]
Ich schließe den Issue, da es keinerlei bestrebungen gibt, aktuell so etwas zu tun. Der Hauptvorteil davon ist auch nicht mehr gegeben, da das Trafficlimit nicht mehr existiert.
