### ISSUE TITLE
Create content area for authenticated users

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#281]
For publishing minutes, budgets etc. in a confidential manner, we would like to have content which is only accessible to authenticated members.

**Comment by lukasjuhrich** [comment]
This would be faily easy to implement, at least from the blueprint side: Just add some view using `login_required`:

```python
@login_required
@bp.route('/internal/<file>')
def internal_documents():
    return "Giving you {}".format(file)
```

Another question is how to “mark” internal documents. I see two possibilities:
1. Using a folder called “internal” or similiar.
Pro: Easy to implement, nothing can go wrong
Con: Not very dynamical.
2. Adding a switch in the metadata of a file/directory
Pro: Dynamical
Con: Harder to implement, Plus, if you mis-write the header data, an internal document may appear visible.

I personally root find possibility one more convincing, since it does the job and we don't really need more complexity to it – the main category would be our meeting minutes, and they can be grouped in such a folder without any disadvantage.

**Comment by marcelb98** [comment]
Is this page (https://agdsn.de/sipa/pages/legal/minutes) then still needed? I think we should replace this page with a new "documents" page.

**Comment by toothstone** [comment]
Btw, I'm heavily in favor of option 1, since it's much more user-friendly and makes it much harder to make mistakes and leak files. We could implement very strict checks for that special directory (e.g. in our monitoring), to continually check that it is not publicly accessible (think webserver misconfiguration etc.).

Please keep in mind that the content repo was public so far. Will we use a different repo for internal documents, or do we need to change that?

Another idea: We could restrict access so that the internal documents are only accessible via obfuscated URLs to further protect us against leaking documents by mistake/oversight. This would of course make the most sense if the internal document listing (containing all the links) is only accessible to authenticated users as well, but as a mitigation measure against guessing/crawling it would be helpful in any case.

**Comment by sebschrader** [comment]
If serving static files is the only thing, that's needed, all the hard work can and should be delegated to Flask, which provides the [`send_from_directory`](http://flask.pocoo.org/docs/0.12/api/#flask.send_from_directory) helper function.

This function is used by Flask itself for its own [static file mechanism](http://flask.pocoo.org/docs/0.12/quickstart/#static-files).

**Comment by sebschrader** [comment]
That should be all, that's needed:

```python
@login_required
@bp.route('/internal/<file>')
def download_internal_file(filename):
    return send_from_directory(app.config['INTERNAL_FILES_FOLDER'],
                               filename, as_attachment=True)
```

**Comment by sebschrader** [comment]
The function handles caching, unicode normalization, content-type, uses the sendfile optimization if the web server supports etc. So please use it, instead of reinventing stuff.

**Comment by toothstone** [comment]
It would be nice if it supports subdirectories like the current [/documents](https://github.com/agdsn/sipa/blob/develop/sipa/blueprints/documents.py).

**Comment by sebschrader** [comment]
> It would be nice if it supports subdirectories the same as the current /documents.

What makes you assume, it doesn't?

**Comment by marcelb98** [comment]
I already tried a bit around and used `send_from_directory`. My plan was to create a directory `contentArea` (like `content` for news). In this directory is a directory `minutes` which contains directories for network, computing, services, ... containing the PDFs.
So the minutes-section on the documents-page can be implemented by looking which files are in the several directories, returning a list like this one:

- network
  - 2018-02-06
  - 2018-01-23
- computing
  - 2018-01-16
  - 2017-12-19

Other stuff like budgets could be handled similar by using other subdirectories of `contentArea`.

**Comment by lukasjuhrich** [comment]
Sorry for jumping in so late, but let me remind you of PR #319 by @fgrsnau. It's just missing some tests IIRC.

**Comment by lukasjuhrich** [comment]
I rebased the work of @fgrsnau and found out the reason it was not working. With that in mind, I want to clear up things a bit.

What sipa does _not_ do on the frontend side is to provide a “content” section that handles content, documents, et cetera. `content/` is only special in that the update hook
On the frontend side, the following entities exist:
- `pages/<category_id>/<article_id>`  asks the categorized_flatpages extension, which is configured to use `app.config['FLATPATES_ROOT']` for the rendered and localized markdown file.
- `documents/<path>` looks in the `documents` subdirectory of the flatpages root, but that is actually independent of the flatpages extension.
- `images/<path>` does the same, only for images

What @fgrsnau did was the following, (almost) trivial addition:
- override the `documents/restricted/<path>` endpoint to reference files under `<flatpages_root>/documents/restricted` with the caveat that a login is required.

In the context of this architecture, the simple thing to do is not to introduce a “separate content section”, but to introduce a separate view in SIPA. Granted, this has the drawback that we would not be able to introduce _pages_ (i.e., markdown files) that wuold be internal, but I personally don't even consider that a feature to be desired. In any case, this is a feature _orthogonal_ to the restricted documents section.

Having cleared that up, I will finish the restricted documents section and would like some feedback on wether or not a restricted _flatpages_ section is required.

**Comment by sebschrader** [comment]
I'd be much happier, if the restricted documents would be in a separate root directory, that is not a subdirectory of the regular directory, both in the file system namespace and the URL namespace.

This limits the potential impact of programming and configuration errors exposing restricted documents trough the normal documents mechanism.

I assume this shouldn't be too hard to do.

**Comment by lukasjuhrich** [comment]
fixed by 99ed21ae4c298b4afd335ee973e4c19a2de17f53

**Comment by sebschrader** [comment]
Have you tried annotating the view function returned by `as_view` the `login_required` decorator? That would safe you from doing checks yourself in the `StaticFiles` view class.

```python
login_required(StaticFiles.as_view(…))
```

**Comment by lukasjuhrich** [comment]
@sebschrader no I have not, no Idea if this would work.

**Comment by toothstone** [comment]
This is not finished. Afaik there is no way to get the content repo to SIPA in a confidential manner, rendering this feature unusable.

**Comment by lukasjuhrich** [comment]
@toothstone this is a false assesment, since the `GIT_SSH` environment variable can use a custom script instead of ssh, which in essence can call `ssh -i <custom-ssh-deploy-key>`.

I've deployed that to our current setup already.
