### ISSUE TITLE
Do we want to re-implement the bustimes feature?

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#29]
The `bustimes.html` temlpate has been deleted in ae9faa0318e9bd772c8433e206f88c9b2c21c365 — but not so the corresponding route and utility function.

Do we want to undelete the template or delete the feature as a whole?
I for myself find that quite useful, although I don't know how necessary this is, since there is an app for this.
On the other hand, code that is already written does no harm.

**Comment by cooox** [comment]
:+1:
