### ISSUE TITLE
Membership termination

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#295]
This is a Transcript from Vincent.

It would be nice to have a separate category for the contact form dealing with the membership's termination.
## General functionality
- In addition to the text boxes for Subject and Message there should be some important questions (see below).
  - The Subject text box can also be omitted or automatically filled with appropriate information.
- For each question there should be provided the following:
  - The text/description for the question itself.
  - Where necessary:  
    More detailed information or a link to the corresponding webpage/document.
  - The possible answers/decisions.
    - drop down menu
    - list with check-boxes
      - possibly with help text via popup or mouse over
    - calendar (for the date)
- Of course this feature should be available in at least German and English.
## Content / Questions asked
- Date:  
  When can we safely disable the internet connection?
- E-mail address:  
  Does the member want to continue using the e-mail address we provide?
- Webspace:  
  Does the member want to continue using the webspace we provide?
- Membership contribution:  
  - If logged in and the member overpaid:
    How should we proceed with the overpaid money?
    - Link to the 'demand for repayment' document?
    - Automatic generation of the document?
    - Member is authenticated, so no photographic identification should be required.
  - If not logged in:
    How should we proceed in the case of overpayment?
    - Member is not authenticated, so a photographic identification would be required.
- (optional) Short Feedback?
- ... more?
## Reasons for this request
- Most of the notifications regarding the membership's termination are created via the contact form.
- Most notifications do not contain all the required information.
  - Not having to ask all the remaining questions --- and provide explanations --- would reduce the work of the support.
  - The members would probably also have to spend less time.
- A general information about the described options on our news page is not going to suffice --- at least IMO.

**Comment by lightning1** [comment]
It should not be possible to terminate the membership online without an login, since this process needs to be verified.
This should obsolete the distinction in the issue between authenticated and unauthenticated users.

**Comment by lukasjuhrich** [comment]
Closed by #408, but the `and` is not an issue-closing verb, so this did not happen automatically.
