### ISSUE TITLE
Pycroft backend

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#297]
This is a broad issue and will perhaps be split up.

Todo:
- [ ] add the pycroft source
- [x] make the enabled sources configurable (perhaps drop `debug_only` to simplify a hell lot of things) (fixed by #298 in f1527b8)

**Comment by Georgeto** [comment]
There is a pull request #379 featuring a pycroft backend.

**Comment by lukasjuhrich** [comment]
Closing as no longer relevant
