### ISSUE TITLE
Make sipa work properly behind a reverse proxy

### ISSUE THREAD

**Issue by sebschrader** [agdsn/sipa#31]
I just tried to make a test instance publicly available behind a reverse proxy. This did not work properly because sipa expects to be hosted under the root '/' and not under a prefix.

Please add the following snippet:
http://flask.pocoo.org/snippets/35/

**Comment by cooox** [comment]
What was the configuration? Flask works in a 'virtual' subfolder and uwsgi without using a middleware.

**Comment by lukasjuhrich** [comment]
@sebschrader I request more details to reproduce this error – I myself got it explicitly *not* working with your suggested solution, but rather with a correct nginx configuration as documented [here](http://flask.pocoo.org/docs/0.10/deploying/uwsgi/#configuring-nginx):
```nginx
server {
    listen 80;
    server_name localhost;
    location = /sipa { rewrite ^ /sipa/; }
    location /sipa { try_files $uri @sipa; }
    location @sipa {
        include uwsgi_params;
        uwsgi_param SCRIPT_NAME /sipa;
        uwsgi_modifier1 30;
        uwsgi_pass sipa:5000;
    }
}                                           
```
I tested this with `nginx:latest` on docker, mounting this file into `/etc/nginx/conf.d` and linking the sipa container to `sipa`.

**Comment by sebschrader** [comment]
To answer both of your comments @cooox and @lukasjuhrich , Flask or Werkzeug may handle the WSGI case successfully, but I am talking about reverse proxying, which uses HTTP.

The referred snippet, @cooox , is BTW not a middleware.

**Comment by sebschrader** [comment]
The configuration was Apache using
```
ProxyPass /sipa/ http://infra-coreos-newton.agdsn:8080/
ProxyPassReverse /sipa/ http://infra-coreos-newton.agdsn:8080/
```

**Comment by lukasjuhrich** [comment]
My bad @sebschrader, I thought everything redirecting requests to another network entity would be a reverse proxy.
I'm going to take care of this tomorrow if possible.

**Comment by sebschrader** [comment]
Well technically there could be and probably are non-HTTP reverse proxys, but usually reverse proxy means HTTP reverse proxy.
