### ISSUE TITLE
Improve language menu on mobile

### ISSUE THREAD

**Issue by timklge** [agdsn/sipa#317]
Don't know why it chose English in the first place, but can't change it to german.

https://drive.google.com/file/d/0BwJFcIalsc1CVktMZEJyUU1GTzA/view?usp=drivesdk

**Comment by lukasjuhrich** [comment]
That's a UI bug. You actually can choose the other language, you just have to scroll the menu down.

Unfortunately, i don't have any ideas on how to make this more apparent.

**Comment by janLo** [comment]
Maybe its working better with the default expanding menu from bootstrap instead of this custom overlay version? Its way more clear that there is more content available when the normal page content gets pushed down while the menu is expanding.

**Comment by lukasjuhrich** [comment]
CNR, google drive link is dead.

_(Also, CNR in general, seems to be fixed :))_
