### ISSUE TITLE
Compute next occurrence of formally defined recurring dates

### ISSUE THREAD

**Issue by janLo** [agdsn/sipa#320]
The meeting dates in [the "Teams" section](https://agdsn.de/sipa/pages/about_us/teams) are in a very unusual way defined (e.g. `Do. 20 Uhr, KW Mod 4 = 3`). This is hard to get and discriminating for a normal human without a technical or mathematical background. A simple solution is, to display the "next" date. 

This can be done by simply show the next date and/or map the date on a calendar widget and/or provide an vCal file. The recurrence rule can be easily defined using [RFC 2445](https://www.ietf.org/rfc/rfc2445.txt). Processing in Sipa can be achieved using [dateutil](https://dateutil.readthedocs.io/en/stable/rrule.html).

**Comment by sebschrader** [comment]
Addressing #363 is a better solution.

**Comment by lukasjuhrich** [comment]
This has been adressed by including the meeting calendar, i.e. #442.
