### ISSUE TITLE
Add Budapester Dormitories

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#322]

**Comment by lightning1** [comment]
The following features are required:

- selection in the contact form
- selection in the login form
- replace finance overview in the usersuite with an "no need to pay" message for related accounts

**Comment by lukasjuhrich** [comment]
@lightning1 The last point will not be possible without creating a separate datasource, since only the datasource is linked to a user. Would it be acceptable to leave the finance row as is (with zero balance)?

**Comment by lightning1** [comment]
@lukasjuhrich I thought about adding an flag to the already existing datasource in question. I think there will be lots of questions regarding payment if the balance is shown.
Apart from the datasource question showing "included in rental agreement" might be better than "no need to pay".
