### ISSUE TITLE
Remove panels in news section

### ISSUE THREAD

**Issue by gwTumm** [agdsn/sipa#33]
The news list is currently formatted using bootstrap panels. I prefer the layout used in the original design at https://agdsn.github.io/newfront-draft2/index.html .
The panels should be used to indicate grouped content whose association the user might not detect himself. In this case, the simple horizontal divider and spacing is completely sufficient and follows the guideline "less is more", imo. The panel outlines do not really fit into the layout, I think.

**Comment by lukasjuhrich** [comment]
:+1:

**Comment by lukasjuhrich** [comment]
I propose to distinguish between “title” and “menutitle” or similiar, because it is reasonable to have something shorter in the navigation bar. The best example for this is imho “FAQ” for the menu title and “Frequently asked questions” for the in-page title.

**Comment by gwTumm** [comment]
Sounds good, but that is another issue, is it?
I just wanted to discuss the news item style in this (minor) issue because I saw the rendered list on some screen a while ago. I actually don't know how the navigation is organized and what it looks like atm since I don't have access to a running test system.

**Comment by lukasjuhrich** [comment]
Actually, you're right. I somehow thought both features would require each other…
Added #34 .
