### ISSUE TITLE
Check for uniqueness of MAC address

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#331]
The Hausübersicht/hades system relies on MAC addresses to be unique, which is currently not checked for  when entering a new MAC address.
It's probably not clever to do this in SIPA itself, but we should use some appropriate pycroft API once available.

**Comment by lukasjuhrich** [comment]
Even in the meantime, this should probably be implemented in the pycroft backend-to-be when such an API does not exist yet.

**Comment by toothstone** [comment]
Is  this now obsolete, as the wu-model is gone? Is this properly handled by pycroft now?

**Comment by lukasjuhrich** [comment]
@toothstone it [appears so](https://github.com/agdsn/pycroft/blob/develop/web/api/v0/__init__.py#L262).

**Comment by toothstone** [comment]
Great, thanks for the pointers!
