### ISSUE TITLE
Traffic-API returns invalid data

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#333]
Under the following conditions the traffic-API returns invalid data:
- user logged in (atlantis-datasource)
- user has no assigned IP (via userstatus)

The displayed traffic data is related to another user that now reuses the old IP.

**Comment by lukasjuhrich** [comment]
This is an obsolete bug that referenced the old `netusers` datasource, which is not in use anymore.
Our current `pycroft` backend does not have and never had this bug.
