### ISSUE TITLE
Add Fritz-Löffler-Straße Dormitory

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#337]

**Comment by toothstone** [comment]
Since GPS is going online tomorrow as well, I would suggest changing the drop-down menu to just:

- Gerokstraße
- Hochschulstraße
- All other student houses

Otherwise it is getting crowded, and we will not have to update for each new house anymore.

**Comment by lukasjuhrich** [comment]
Huhu, I thought I commented on this one already…
The addition of the FL is trivial, you just need to add another dormitory.
Switching the drop-down menu as described would require a small change in logic, as currently it only lists all the dormitories, and not the datasources as suggested.
