### ISSUE TITLE
Sprache basierend auf Browsersprache wählen

### ISSUE THREAD

**Issue by Paktosan** [agdsn/sipa#342]
Als Nutzer möchte ich,
dass die Sprache der Webseite automatisch an die meines Browsers angepasst wird, sofern ich sie nicht manuell ändere,
damit ich nicht bei jedem Besuch händisch von Englisch auf Deutsch wechseln muss.

**Comment by toothstone** [comment]
Hallo,
SIPA sollte die Sprachwünsche deines Browsers bereits berücksichtigen (den `Accept-Language`-Header).
Bitte schau einmal auf https://aruljohn.com/language.php, welche Sprachen dein Browser in welcher Reihenfolge anfordert. Evtl. musst du in den Einstellungen Deutsch (`de`) hinzufügen oder höher priorisieren.

**Comment by Paktosan** [comment]
<img width="589" alt="bildschirmfoto 2017-10-13 um 09 35 23" src="https://user-images.githubusercontent.com/4009269/31535074-e2af9748-aff9-11e7-9bec-8f6a8c76667a.png">
Wie im Bild zu sehen, gibt Safari Deutsch als Sprache an Webseiten, dennoch bekomme ich die Webseite standardmäßig in Englisch präsentiert.

**Comment by toothstone** [comment]
Anscheinend ist SIPA zu strikt bei der Auswahl der Locale, sodass nur `de` als passender Header-Eintrag erkannt wird (`de-de` und `de-DE`, die nach meinem Verständnis von BCP47 etc. gültig sind, werden nicht erkannt).
Als Workaround könntest du `de` als gewünschte Sprache in deinem Browser hinzufügen, aber wir werden uns die entsprechende Logik in `sipa/sipa/base.py` und `sipa/sipa/babel.py` mal anschauen müssen.
