### ISSUE TITLE
Insert correct language attribute in `html` tag

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#343]
While investigating #342 I noticed that SIPA always replies with
`<html lang="de" xmlns="http://www.w3.org/1999/html">`
no matter which language is actually used.

How to reproduce:
`curl --header "Accept-Language: en" https://agdsn.de/sipa/news/`

**Comment by aekazitt** [comment]
Let me look into this. Most likely caused by babel.py

**Comment by lukasjuhrich** [comment]
No, the reason is that it's just a hard-coded html tag. Just look at the template: https://github.com/agdsn/sipa/blob/develop/sipa/templates/base.html#L27
