### ISSUE TITLE
Correct cache information

### ISSUE THREAD

**Issue by JuKu** [agdsn/sipa#361]
If you are logged in and activate cache [1], their isn't any information, that the cache is currently only for steam. Please add this information or rename it to "Steam Cache".

[1] https://agdsn.de/sipa/usersuite/#hot-buttons

**Comment by toothstone** [comment]
Although this is mainly a content-related task (which is not tracked here), a few changes (including a link etc.) need to be made in the code itself. This could be a good introduction to this project, maybe one of our newbies is interested (@JuKu @marcelb98 ...)?

**Comment by marcelb98** [comment]
Maybe we should also create a page which describes the cache in short (like Services > Webhosting). In the future we could list on this page all services which are cached.

**Comment by toothstone** [comment]
> Maybe we should also create a page which describes the cache in short (like Services > Webhosting). In the future we could list on this page all services which are cached.

This is exactly what I meant in relation to the content-repo. @JuKu said he would look into that.

**Comment by toothstone** [comment]
I just realized the content was already [added](https://git.agdsn.de/sipa-content/content/commit/85c81b702c8e148229861c64f9d8f108f2e5ae8f). Thanks!

So now all is left is linking that page in the notifications during the activation process, and ensuring the language used (en and de!) is consistent with the content page.
