### ISSUE TITLE
Connect SIPA to our CalDAV-Server

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#363]
It should be possible to get the upcoming events from our internal NextCloud-instance via CalDAV. This might provide some benefits, including the public announcement of non-regular events like "Technikführungen" and no news for extra office hours are required anymore, since they are displayed automatically.

Two subsections would be interesting include a calendar module: "Support -> Office Hours" and "About Us -> Teams".
In the NextCloud a new calendar should be created to separate internal and public events. The connection of SIPA and the NextCloud should use our internal network.

**Comment by lukasjuhrich** [comment]
This has been adressed by including the meeting calendar, i.e. #442.
