### ISSUE TITLE
Display the specific payment details for a logged in account 

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#365]
Incorrect purpose specifications in transfers are a PITA for our treasurers, and it should be easily possible to display the correct information for a logged in user, maybe even for a user connecting from his/her room.

**Comment by toothstone** [comment]
Pinging @Paktosan @ibot3 @marcelb98 just in case.

**Comment by mmarx** [comment]
Please make sure to correctly handle members not living in any specific room.
