### ISSUE TITLE
Fix overlapping menu in usersuite

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#368]
Since the top menu is kept attached to the upper edge of the screen, it is obscuring the headings in the usersuite when visiting a section via the usersuite submenu or a permalink.

**Comment by sebschrader** [comment]
Darn, referenced this issue from the wrong commit, should have been 3e2f1458b5e14dcc57f3ec500acaf4fc23e77833 instead of ff8fb9094e384278d5b01db0aa9982b2a6175691.
