### ISSUE TITLE
Allow self-enabling of network access (or other services)

### ISSUE THREAD

**Issue by Lodifice** [agdsn/sipa#385]
We have recently come to the conclusion that our services form is optional.
Members shall be able to get network access if they write us an E-mail with their MAC address and date of birth.

It would be beneficial if there was an online form for enabling network access.
This would have several advantages, e.g., no E-Mails have to be processed, there can be sanity checks, the effect is instant.

Since changing the MAC address is already possible, this should not be so hard and involve mainly UI changes.

**Comment by ibot3** [comment]
I implemented an API resource for this in pycroft.
It takes `password`, `birthdate`, `mac` and `host_name`.

**Comment by Lodifice** [comment]
Since #389 is merged, shouldn't this be solved?
