### ISSUE TITLE
Add 'description' to payment details

### ISSUE THREAD

**Issue by marcelb98** [agdsn/sipa#386]
In the english usersuite 'description' should be added to 'Purpose/Intented use' in the payment details.

**Comment by lukasjuhrich** [comment]
What do you mean by “should be added”? Do you want to add the word, as in `Purpose/Indended use/Description`, or do you mean a new column?

**Comment by marcelb98** [comment]
Yes, the word should be added so that the existing column is called `Purpose/Indended use/Description`.

**Comment by toothstone** [comment]
Just some background info: My main motivation for this exhaustive labeling was mainly to prevent people from using the 'Reference' field, back when it was not evaluated by Pycroft. So we could cut back on this, but of course consistency should be the main concern here.
