### ISSUE TITLE
User membership cancellation doesn't work at some days

### ISSUE THREAD

**Issue by Floyer007** [agdsn/sipa#409]
It's not possible to cancel the membership via SiPa, if the given Date is 2019-10-01.
The calculated balance stays empty and a error-message "invalid balance" is displayed.

2019-10-02 doesn't work, too.
If this is a feature and not a bug, there should be a proper error-message for the user:
e.g. "We recommend to cancel the membership at the End of a month. Otherwise you have to pay for the following month, too."

![Screenshot_2019-09-20 AG DSN - Mitgliedschaft beenden - Bestätigen](https://user-images.githubusercontent.com/8080648/65332737-89e16f80-dbbf-11e9-9244-c25011055598.png)

**Comment by ibot3** [comment]
For some reason the form field did not get filled out if the estimated balance was `0.0`.
Fixed with 473721d47ff2dfe41292920d23733c08cfe08ae2
