### ISSUE TITLE
improve status information in sidebar

### ISSUE THREAD

**Issue by marcelb98** [agdsn/sipa#413]
We're posting all planned outages on our statuspage, so it would be nice if these planned events would be also shown on the homepage of SIPA (so we wouldn't have to write an extra SIPA news for the outages).

Maybe the planned events are also available in the API of Cachet.

**Comment by LukasGibeh** [comment]
It would be nice if the names of dormitories affected by outages or planned maintenance are also displayed in the sidebar if the problem/maintenance only affects one or two dormitories.
e.g. "There is currently a partial outage in XXX" instead of just "There is currently a partial outage."

**Comment by marcelb98** [comment]
The affected dormitories are already shown in a popup after hovering over the message that there's a partial outage. I think this is the best solution since the sidebar would be overloaded otherwise.

**Comment by ibot3** [comment]
But one could display the affected dormitories without a popup.

**Comment by marcelb98** [comment]
Done with  3cf66ca
