### ISSUE TITLE
Add St. Petersburger Straße to login dormitory selection

### ISSUE THREAD

**Issue by Paktosan** [agdsn/sipa#427]
SPS is missing from the dormitory selection when logging in.
This causes confusion with members.
We should at it to the list.
Even better would be to get rid of the selection of dormitory all together as described in #426.

**Comment by lukasjuhrich** [comment]
Refs #414 (#426 was a duplicate)

**Comment by ibot3** [comment]
I already added it in an recent commit. It's just not yet deployed.

**Comment by lukasjuhrich** [comment]
@ibot3 Let me passive-aggressively rephrase that for you:
„I fixed it in recent commits but forgot to add a reference to the issue. The commits in question are 3171591641d01241a6f2d6f81416c927ebac485c and b8d11887ee35288e51924f07a0264514fb7a0afc“ ;)

Closing as it's already in `develop`.

**Comment by lukasjuhrich** [comment]
(Anyway, thanks for fixing that so quickly!)
