### ISSUE TITLE
Start uwsgi and http from the same file

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#46]
When starting the http service itself from docker, one has to explicitly provide the entry point as `python sipa.py`. Better would be reading an environment variable like `SIPA_UWSGI`.

**Comment by sebschrader** [comment]
This would be a command and not an entrypoint. See https://docs.docker.com/reference/builder/#cmd vs. https://docs.docker.com/reference/builder/#entrypoint

I do not agree that the sipa.py file should handle all this deployment plumbing and be configurable to start an UWSGI server. sipa.py should expose an WSGI app or run in debug mode if run as __main__ like it does now.

If you want to make it easier for the user of the docker image, you can provide a second Dockerfile which uses the current docker image as base and just has a different CMD instruction.

**Comment by janLo** [comment]
Just provide a dockerfile with another uwsgi config. Uwsgi is able to
provide a uwsgi or a http socket.

**Comment by sebschrader** [comment]
You still want to be able to run the built-in HTTP server of Flask. You can not use the werkzeug debugger together with UWSGI.

**Comment by lukasjuhrich** [comment]
@sebschrader first of all, I planned to include this in the `start.sh`, of course not in the `sipa.py`. I do not see why I should create a whole new docker image instead of just passing one environment variable. Does what you described as “deployment plumbing” still hold for using `start.sh`?

I do not really get your point, because I do not see why it is invalid to use an environment variable to switch between different configurations.

**Comment by sebschrader** [comment]
Well adding the environment variable surely isn't enough. You have to write code that uses that variable right? Either in Python code or shell code. And then you have to write documentation for that environment variable.

Currently the SIPA is still quite simple. You have sipa.py which exports an WSGI app object, that any WSGI server such as uWSGI can use it. And there is special case that allows you to run sipa.py directly on the command-line for development/debugging purposes. I would keep it that way.

**Comment by lukasjuhrich** [comment]
That's almost how it is. Currently, there *is* as `start.sh`, which is the standard comand for docker, which starts uwsgi and uses the app object from `sipa.py`. So it would make it no more complicated in my opinion to add some three lines checking for that environment variable.
Also, documentation has to be updated anyways, it is quite behind I guess.

**Comment by sebschrader** [comment]
I don't see why a single command was moved into a separate start.sh file.

**Comment by sebschrader** [comment]
You can always override the command (and more) on the docker command line. See https://docs.docker.com/reference/run/#overriding-dockerfile-image-defaults

**Comment by lukasjuhrich** [comment]
I don't know why it exists, that was just the current state by which I was arguing. Removing it would be a possibility, and if its removed, your arguments seem valid.

**Comment by sebschrader** [comment]
Great, then remove it and use the chdir argument of uwsgi to replace the cd from start.sh

**Comment by sebschrader** [comment]
Please see my line commet in 010db15
