### ISSUE TITLE
Show correct date of finance balance

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/sipa#468]
Currently, the "last updated" resp. "Stand" date is the date the last bank import happened.  This might be confusing b/c only transactions until the day before (or even two or three days before if the import happens at a Sun- or Monday) are considered.  IMO the German wording is even worse as "Stand" would translate to something like "as of" which sounds like the specified date is included.

I suggest the following:
1. show the date a transaction must have arrived at our bank account to be displayed
2. adjust wording to be correct and easier understandable (maybe not be necessary but helpful if 1. is done)

Suggestion for a long but IMO explicit and understandable wording:

DE: `enthält bis zum {{ date }} auf unserem Konto eingegangene Überweisungen`\
EN: `contains transactions arrived at our bank account up to and including {{ date }}`

**Comment by agmes4** [comment]
I see it as an information which should be shown when ever you hover over the amount or do you think this is still to confusing for some people?

**Comment by FestplattenSchnitzel** [comment]
I think most people won't hover over the relevant part, or won't entirely (e.g. mobile devices).  The best idea would probably be to show some subtle text (e.g. gray, smaller font size) below "Current MAC address" in the left column of the "Status information" table.  This could also be reused for https://github.com/agdsn/sipa/issues/480 .
