### ISSUE TITLE
Implement changing parameters in model.sample

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#47]
Currently, `model.sample` does not provide a possibility to edit the parameters such as the mac address. This would be nice, because then all frontend features could be tested (and bugs found and fixed) without having to set up a more complicated environment such as in `model.wu`, requiring additional data sources.

I believe something like a `ConfigParser` would be sufficient.

**Comment by sebschrader** [comment]
I have no idea what this issue is about. Could you be a bit more descriptive?

**Comment by lukasjuhrich** [comment]
Alright, I updated the description.
