### ISSUE TITLE
Provide more details to "Current MAC address" field in "Status information"

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/sipa#480]
There were people that thought they'd need to enter their phones MAC address in order to be able to use the WLAN.  I can understand this confusion to some extend and think we should provide more details next to the field as well as the form for changing.

(thanks @jnsga)

**Comment by agmes4** [comment]
![2023-12-23_21-58](https://github.com/agdsn/sipa/assets/61407455/699dc3ed-1614-4aa1-9a1c-83ff4f8f0273)
I thing this should be working
