### ISSUE TITLE
Evaluate dropping jQuery

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/sipa#488]
jQuery isn't required (any more) in Bootstrap 5 [0] and pygal-tooltips seems to work without [1] but we seem to use it in

* [sipa/static/js/register_identify.js](https://github.com/agdsn/sipa/blob/3c87aa49c2255785e181e2e65c742cdd9ffd4931/sipa/static/js/register_identify.js) as well as
* [sipa/static/js/contact-hints.js](https://github.com/agdsn/sipa/blob/develop/sipa/static/js/contact-hints.js).

[0] https://getbootstrap.com/docs/5.3/getting-started/javascript/#optionally-using-jquery
[1] https://www.pygal.org/en/3.0.0/documentation/web.html

**Comment by lukasjuhrich** [comment]
Sure, that would be a good idea.
In that vein, the scripts should be simplified using modern syntax (arrow functions, `let/const` instead of `var`, …)
