### ISSUE TITLE
Create data source plugin for HSS databases

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#49]
SIPA has to access postgres- and ldap-data from Abe (HSS-Database host) in order to be useful to HSS-users.

**Comment by lukasjuhrich** [comment]
Any updates on this? I haven't heard about any progress lately, please keep the communication up.

**Comment by lukasjuhrich** [comment]
Closing, since the details are handled in other issues and for the whole thing, there exists a milstone now.
