### ISSUE TITLE
Choose the division when logging in

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#50]
Instead of running a separate instance for each division, using a drop-down menu in the login page seems to be the better way.

One should think about a mechanism to register the divisions in order to provide useful information, such as where the initialization function lies or different things, but there are many possibilities to accomplish this. Additionally, the `sample` division should only be made available in **debug mode**! 

Also, one has to find a possibility to store not only the `uid`, but also the `division` in the user's cookie.

**Comment by sebschrader** [comment]
Why couldn't SIPA detect the division of the user?

An option to change the division temporarily could be done too, to allow the user to browse information of other division. On the other hand, this could also be very dangerous, if it would unlock features, that don't make sense for somebody from another division (e.g. control of MySQL on Helios for non-Wu users)

**Comment by lightning1** [comment]
SIPA can preselect the division of a user using the ip address, but external logins should be possible, too.
The selections purpose is separating the different data source methods for divisions, not for the information displayed on the normal help pages.

**Comment by lukasjuhrich** [comment]
Wait, I totally forgot about the `/content` pages. These have to be separated as well if such a workflow is preferred, which would be a lot more work. Also, users want to be able to see pages without having to log in, which would be impossible to realize without any major possibility of distinction, like a splash-screen combined with a drop-down menu like for the language.

To sum up, there seem to be two possibilities:

- Leave everything the way it is, and let each division run their own instance of Sipa.
- Implementing a splash-screen and a drop-down menu, saving the choice in the user's session cookie and switching the content source as well as the login backend accordingly.

**Comment by lightning1** [comment]
That is exactly what i was talking about. No separation of content-pages is necessary, according to the SIPA-content-meeting. The basic idea for SIPA is to reduce differences between divisions, so distinct pages would be a no-go.
Just the data displayed after the login (usersuite) have to be customizable.

**Comment by lukasjuhrich** [comment]
@lightning1: I was not aware of this decision, but it makes things significantly easier. A splash screen does not seem to be necessary then.

@sebschrader could you perhaps clarify what you mean by “unlock features”? It is not planned, that an _authenticated user_ can change his/her division, but that a _visitor of then website_ can choose which session he is in. If he chooses the “wrong” one, the authentication would fail. The information displayed in the usersuite will not be affected any more than it already is by providing different login backends.

**Comment by sebschrader** [comment]
Well, then a simple dropdown on the login page should be sufficient.
We could make a preselection based on the IP address.

**Comment by lukasjuhrich** [comment]
Indeed, a preselection would be nice. I will implement it.
