### ISSUE TITLE
Maximum amount for Membership

### ISSUE THREAD

**Issue by agmes4** [agdsn/sipa#500]
# Bug 
the Pay membership contribution for has no maximum that can be set. So when there a very high value for example 199999999999999999999999999999999999999999999999999999999999999999 it gives 500 error. there can only be 26 letters in after that you get the error. 

## Hints 
we need to validate the value so set a lower one else return an error

**Comment by FestplattenSchnitzel** [comment]
Fixed with https://github.com/agdsn/sipa/commit/cf11d9879ed161f60156ac3662e296ab55d4c606 .
