### ISSUE TITLE
Rename dormitory login

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#56]
The dropdown box at the login page should not select the division, but the dormitory the member lives in. The goal is to not support old ag dsn structures.

**Comment by lukasjuhrich** [comment]
Do you mean to separate the dormitories of each division (for instance “Wundtstraße & Zellescher Weg” → “Wundtstraße”, “Zellescher Weg”), or do you mean to just rename the label of the select field to “dormitory”?

**Comment by lightning1** [comment]
I think both would be a good solution, since Borsbergstraße will join the data source module soon.

**Comment by lukasjuhrich** [comment]
Alright, so this requires some kind of abstraction or at least distinction between dormitories and divisions.

**Comment by Janluak** [comment]
It should be dormitory "Wundtstraße", "Zellescher Weg" and "Bosbergstraße". All of those for example will use the same db. The code can be the same, simply the user will see a difference

**Comment by toothstone** [comment]
I'm not up to date, but why do users need to specify their dorm/division at all?

**Comment by lukasjuhrich** [comment]
@toothstone It is needed in order to login, because Sipa has to know which datasource (`wu`, `hss`, …) to choose to process the login.

**Comment by toothstone** [comment]
Can't we just try all of them? I highly doubt anyone has a valid account in two dbs.

**Comment by lukasjuhrich** [comment]
No, but still, anyone can choose any valid username. It is technically possible to get duplicates.

**Comment by sebschrader** [comment]
You could still try all backends.
If at least one succeeds the user is logged in, otherwise he's not.
For security reasons, you the error message presented to the user in case of authentication failure should not distinguish between user exist and password is wrong anyway.
