### ISSUE TITLE
Correct alignment of traffic gauge

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#7]
The current arc is bigger than π, which looks totally off and overlaps with the units displayed.

**Comment by lukasjuhrich** [comment]
**CNR**, see picture
![screenie](https://cloud.githubusercontent.com/assets/10060406/7202621/6e19a480-e514-11e4-8d8f-c08c1479808e.png)

**Comment by toothstone** [comment]
Well...

![gauge](https://cloud.githubusercontent.com/assets/4670824/7202726/3d023e6a-e515-11e4-8041-badb09e4f226.jpg)
(Chromium, chrome beta, iceweasel)

**Comment by lukasjuhrich** [comment]
Chromium:
![chrome](https://cloud.githubusercontent.com/assets/10060406/7202849/4ea6b884-e516-11e4-87ef-bfe1b4c475e3.png)
still CNR
Seems very strange.
(sorry to say so, but that made me lol anyway…)

**Comment by toothstone** [comment]
I remember @gwTumm addressing this once, I think he built the gauge as well.

**Comment by lukasjuhrich** [comment]
The gauge is not custom built, see [this page](http://justgage.com/)

**Comment by lukasjuhrich** [comment]
JS debugging && looking into your browser's logs might clear things up(?)

**Comment by lukasjuhrich** [comment]
Oh **That**'s been the issue… thx @gwTumm
