### ISSUE TITLE
Route links in pages correctly if run not under root url

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#79]
If sipa is run under a prefix such as `sipa`, the links in the content pages don't refer to the correct spot.

**Comment by Janluak** [comment]
sipa is not to run with a prefix. It is going to run directly as agdsn.de <http://agdsn.de/>



Bis dann

Jan

**Comment by lukasjuhrich** [comment]
@Janluak Please note that for the current (test) deployment, this is absolutely necessary in order to test this feature (accessibility of `/documents/*`). We cannot risk only testing a feature when sipa goes live.

Also, a software claiming to be a web application should support being run with a url prefix in every case, this is basic functionality.

**Comment by mmarx** [comment]
^- This.

**Comment by lukasjuhrich** [comment]
There is no useful fix for this, at least no beautiful one. This can be avoided using relative paths in the flatpages though.
