### ISSUE TITLE
Do not hide link to `/usertraffic`

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#8]
Under the traffic gauge, there is a link to `/usertraffic` which is hidden when no traffic data can be queried. Not hiding it would be better though, because the latter site redirects according to whether traffic data can be retrieved and whether the user is logged in appropriately already.
Thus, hiding the link in certain situations is unnecessarily confusing.

**Comment by toothstone** [comment]
Furthermore I would prefer not to show an extra link, but rather reference /usertraffic from the whole chart.

**Comment by lukasjuhrich** [comment]
@toothstone what do you mean by “reference”? Wrapping the whole chart with `<a></a>`?

**Comment by toothstone** [comment]
If that works, yes.

**Comment by lukasjuhrich** [comment]
Besides, let me hear your opinion about removing the huge “Traffic” headline because that's somewhat redundant – and furthermore, “less is more” ;)

**Comment by toothstone** [comment]
Sure, do it, "spent traffic" is enough.
