### ISSUE TITLE
`/usertraffic` claims another user would be logged in than is fetched via IP

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#93]

**Comment by toothstone** [comment]
Is this supposed to be the 'Another user than the one registered for this connection is logged in!'-bug at /usertraffic?

**Comment by lukasjuhrich** [comment]
Yes, it is. is this a duplicate?

**Comment by toothstone** [comment]
No, it's just that the current title is misleading, the gauge doesn't claim anything. /usertraffic does.
