### ISSUE TITLE
Account status not localized

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#96]
Account status always appears as (e.g.) "Bezahlt, verbunden".

**Comment by toothstone** [comment]
As of right now, account status is still not localized.

**Comment by lukasjuhrich** [comment]
@toothstone It works for me. Perhaps you did not check on `sipa-testing`?

Please prove that things are reproducible before reopening.

**Comment by toothstone** [comment]
Hm, may have been a cached version...

**Comment by lukasjuhrich** [comment]
Our current installation (`/sipa`) is kept on a stable point, and therefore in a way “cached”. For the purpose of actuality, `/sipa-testing` has been set up.
