### ISSUE TITLE
Hide pagination buttons if there is nothing to other page

### ISSUE THREAD

**Issue by janLo** [agdsn/sipa#98]
Showing complete useless disabled buttons is more a UI fail than a feature. Just hide the buttons if there is no other page.

![page](https://cloud.githubusercontent.com/assets/96146/9983700/47b83c2a-6007-11e5-8eab-8d2ee899ca28.png)

**Comment by lukasjuhrich** [comment]
Do you suggest to hide each button separately? I recall that when I tried this, the page seemed to be out of symmetry.
