### ISSUE TITLE
Wu: Display multiple hosts

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#99]
The usersuite should support multiple devices per user. If there is more than one host record, a table beneath the normal user info would be great.

This is labeled a bug, because multiple hosts result in a need to accumulate the traffic per user.

**Comment by lukasjuhrich** [comment]
@lightning1 As I am refactoring the user class right now,  I notice that this change is not trivial at all, since the code expects there to be only one IP for most of the changes making use of a MySQL query  (e.g. `mac.setter`). This needs further elaboration.
